dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
filename: "mock_{{.InterfaceName}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/poymanov/codemania-task-board/board/internal/domain/board:
    config:
      include-interface-regex: .*Repository
  github.com/poymanov/codemania-task-board/board/internal/domain/column:
    config:
      include-interface-regex: .*Repository
