// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/poymanov/codemania-task-board/board/internal/domain/board"
	mock "github.com/stretchr/testify/mock"
)

// NewBoardRepository creates a new instance of BoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoardRepository {
	mock := &BoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BoardRepository is an autogenerated mock type for the BoardRepository type
type BoardRepository struct {
	mock.Mock
}

type BoardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BoardRepository) EXPECT() *BoardRepository_Expecter {
	return &BoardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type BoardRepository
func (_mock *BoardRepository) Create(ctx context.Context, newBoard board.NewBoard) (int, error) {
	ret := _mock.Called(ctx, newBoard)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, board.NewBoard) (int, error)); ok {
		return returnFunc(ctx, newBoard)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, board.NewBoard) int); ok {
		r0 = returnFunc(ctx, newBoard)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, board.NewBoard) error); ok {
		r1 = returnFunc(ctx, newBoard)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BoardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BoardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newBoard board.NewBoard
func (_e *BoardRepository_Expecter) Create(ctx interface{}, newBoard interface{}) *BoardRepository_Create_Call {
	return &BoardRepository_Create_Call{Call: _e.mock.On("Create", ctx, newBoard)}
}

func (_c *BoardRepository_Create_Call) Run(run func(ctx context.Context, newBoard board.NewBoard)) *BoardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 board.NewBoard
		if args[1] != nil {
			arg1 = args[1].(board.NewBoard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BoardRepository_Create_Call) Return(n int, err error) *BoardRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *BoardRepository_Create_Call) RunAndReturn(run func(ctx context.Context, newBoard board.NewBoard) (int, error)) *BoardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByOwnerId provides a mock function for the type BoardRepository
func (_mock *BoardRepository) GetAllByOwnerId(ctx context.Context, ownerId int) ([]board.Board, error) {
	ret := _mock.Called(ctx, ownerId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByOwnerId")
	}

	var r0 []board.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]board.Board, error)); ok {
		return returnFunc(ctx, ownerId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []board.Board); ok {
		r0 = returnFunc(ctx, ownerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]board.Board)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, ownerId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BoardRepository_GetAllByOwnerId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByOwnerId'
type BoardRepository_GetAllByOwnerId_Call struct {
	*mock.Call
}

// GetAllByOwnerId is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerId int
func (_e *BoardRepository_Expecter) GetAllByOwnerId(ctx interface{}, ownerId interface{}) *BoardRepository_GetAllByOwnerId_Call {
	return &BoardRepository_GetAllByOwnerId_Call{Call: _e.mock.On("GetAllByOwnerId", ctx, ownerId)}
}

func (_c *BoardRepository_GetAllByOwnerId_Call) Run(run func(ctx context.Context, ownerId int)) *BoardRepository_GetAllByOwnerId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BoardRepository_GetAllByOwnerId_Call) Return(boards []board.Board, err error) *BoardRepository_GetAllByOwnerId_Call {
	_c.Call.Return(boards, err)
	return _c
}

func (_c *BoardRepository_GetAllByOwnerId_Call) RunAndReturn(run func(ctx context.Context, ownerId int) ([]board.Board, error)) *BoardRepository_GetAllByOwnerId_Call {
	_c.Call.Return(run)
	return _c
}
