// Code generated by ogen, DO NOT EDIT.

package gateway_v1

import (
	"fmt"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/BadRequestError
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) boardCreateRes()  {}
func (*BadRequestError) boardGetAllRes()  {}
func (*BadRequestError) columnCreateRes() {}
func (*BadRequestError) columnDeleteRes() {}

// ColumnDeleteNoContent is response for ColumnDelete operation.
type ColumnDeleteNoContent struct{}

func (*ColumnDeleteNoContent) columnDeleteRes() {}

// Ref: #/components/schemas/CreateBoardRequestBody
type CreateBoardRequestBody struct {
	// Название доски.
	Name string `json:"name"`
	// Описание доски.
	Description string `json:"description"`
	// ID автора доски.
	OwnerID int `json:"owner_id"`
}

// GetName returns the value of Name.
func (s *CreateBoardRequestBody) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateBoardRequestBody) GetDescription() string {
	return s.Description
}

// GetOwnerID returns the value of OwnerID.
func (s *CreateBoardRequestBody) GetOwnerID() int {
	return s.OwnerID
}

// SetName sets the value of Name.
func (s *CreateBoardRequestBody) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateBoardRequestBody) SetDescription(val string) {
	s.Description = val
}

// SetOwnerID sets the value of OwnerID.
func (s *CreateBoardRequestBody) SetOwnerID(val int) {
	s.OwnerID = val
}

// Ref: #/components/schemas/CreateBoardResponse
type CreateBoardResponse struct {
	// ID созданной доски.
	BoardID int `json:"board_id"`
}

// GetBoardID returns the value of BoardID.
func (s *CreateBoardResponse) GetBoardID() int {
	return s.BoardID
}

// SetBoardID sets the value of BoardID.
func (s *CreateBoardResponse) SetBoardID(val int) {
	s.BoardID = val
}

func (*CreateBoardResponse) boardCreateRes() {}

// Ref: #/components/schemas/CreateColumnRequestBody
type CreateColumnRequestBody struct {
	// Название колонки.
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *CreateColumnRequestBody) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CreateColumnRequestBody) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/CreateColumnResponse
type CreateColumnResponse struct {
	// ID созданной колонки.
	ColumnID int `json:"column_id"`
}

// GetColumnID returns the value of ColumnID.
func (s *CreateColumnResponse) GetColumnID() int {
	return s.ColumnID
}

// SetColumnID sets the value of ColumnID.
func (s *CreateColumnResponse) SetColumnID(val int) {
	s.ColumnID = val
}

func (*CreateColumnResponse) columnCreateRes() {}

// Ref: #/components/schemas/GenericError
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

type GetAllBoardResponse []GetAllBoardResponseItem

func (*GetAllBoardResponse) boardGetAllRes() {}

type GetAllBoardResponseItem struct {
	// ID доски.
	ID int `json:"id"`
	// Название доски.
	Name string `json:"name"`
	// Описание доски.
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *GetAllBoardResponseItem) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *GetAllBoardResponseItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *GetAllBoardResponseItem) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *GetAllBoardResponseItem) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *GetAllBoardResponseItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *GetAllBoardResponseItem) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/InternalServerError
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) boardCreateRes()  {}
func (*InternalServerError) columnCreateRes() {}
func (*InternalServerError) columnDeleteRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
