// Code generated by ogen, DO NOT EDIT.

package gateway_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	BoardCreateOperation          OperationName = "BoardCreate"
	BoardGetAllOperation          OperationName = "BoardGetAll"
	ColumnCreateOperation         OperationName = "ColumnCreate"
	ColumnDeleteOperation         OperationName = "ColumnDelete"
	ColumnUpdatePositionOperation OperationName = "ColumnUpdatePosition"
	TaskCreateOperation           OperationName = "TaskCreate"
)
