// Code generated by ogen, DO NOT EDIT.

package gateway_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BoardCreate implements BoardCreate operation.
//
// Создание доски.
//
// POST /api/v1/boards
func (UnimplementedHandler) BoardCreate(ctx context.Context, req *CreateBoardRequestBody) (r BoardCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BoardGetAll implements BoardGetAll operation.
//
// Получение досок.
//
// GET /api/v1/boards
func (UnimplementedHandler) BoardGetAll(ctx context.Context) (r BoardGetAllRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ColumnCreate implements ColumnCreate operation.
//
// Создание колонки.
//
// POST /api/v1/boards/{id}/columns
func (UnimplementedHandler) ColumnCreate(ctx context.Context, req *CreateColumnRequestBody, params ColumnCreateParams) (r ColumnCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
