// Code generated by ogen, DO NOT EDIT.
package gateway_v1

type BoardCreateRes interface {
	boardCreateRes()
}

type BoardGetAllRes interface {
	boardGetAllRes()
}

type ColumnCreateRes interface {
	columnCreateRes()
}

type ColumnDeleteRes interface {
	columnDeleteRes()
}
