// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: board/v1/board.proto

package board_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание доски
type BoardServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название доски
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Описание доски
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateRequest) Reset() {
	*x = BoardServiceCreateRequest{}
	mi := &file_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateRequest) ProtoMessage() {}

func (x *BoardServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Ответ на создание доски
type BoardServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateResponse) Reset() {
	*x = BoardServiceCreateResponse{}
	mi := &file_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateResponse) ProtoMessage() {}

func (x *BoardServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardServiceCreateResponse) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

var File_board_v1_board_proto protoreflect.FileDescriptor

const file_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x14board/v1/board.proto\x12\bboard.v1\x1a\x17validate/validate.proto\"\x87\x01\n" +
	"\x19BoardServiceCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescription\x12\"\n" +
	"\bowner_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\aownerId\"7\n" +
	"\x1aBoardServiceCreateResponse\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\x03R\aboardId2c\n" +
	"\fBoardService\x12S\n" +
	"\x06Create\x12#.board.v1.BoardServiceCreateRequest\x1a$.board.v1.BoardServiceCreateResponseBFZDgithub.com/poymanov/codemania-task-board/pkg/proto/board/v1;board_v1b\x06proto3"

var (
	file_board_v1_board_proto_rawDescOnce sync.Once
	file_board_v1_board_proto_rawDescData []byte
)

func file_board_v1_board_proto_rawDescGZIP() []byte {
	file_board_v1_board_proto_rawDescOnce.Do(func() {
		file_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)))
	})
	return file_board_v1_board_proto_rawDescData
}

var (
	file_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_board_v1_board_proto_goTypes  = []any{
		(*BoardServiceCreateRequest)(nil),  // 0: board.v1.BoardServiceCreateRequest
		(*BoardServiceCreateResponse)(nil), // 1: board.v1.BoardServiceCreateResponse
	}
)

var file_board_v1_board_proto_depIdxs = []int32{
	0, // 0: board.v1.BoardService.Create:input_type -> board.v1.BoardServiceCreateRequest
	1, // 1: board.v1.BoardService.Create:output_type -> board.v1.BoardServiceCreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_board_v1_board_proto_init() }
func file_board_v1_board_proto_init() {
	if File_board_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_board_v1_board_proto_goTypes,
		DependencyIndexes: file_board_v1_board_proto_depIdxs,
		MessageInfos:      file_board_v1_board_proto_msgTypes,
	}.Build()
	File_board_v1_board_proto = out.File
	file_board_v1_board_proto_goTypes = nil
	file_board_v1_board_proto_depIdxs = nil
}
