// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: board/v1/board.proto

package board_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание доски
type BoardServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название доски
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Описание доски
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateRequest) Reset() {
	*x = BoardServiceCreateRequest{}
	mi := &file_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateRequest) ProtoMessage() {}

func (x *BoardServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Запрос на получение всех досок по ID владельца
type BoardServiceGetAllByOwnerIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceGetAllByOwnerIdRequest) Reset() {
	*x = BoardServiceGetAllByOwnerIdRequest{}
	mi := &file_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceGetAllByOwnerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceGetAllByOwnerIdRequest) ProtoMessage() {}

func (x *BoardServiceGetAllByOwnerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceGetAllByOwnerIdRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceGetAllByOwnerIdRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardServiceGetAllByOwnerIdRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Ответ со списком всех досок владельца
type BoardServiceGetAllByOwnerIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список досок
	Boards        []*Board `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceGetAllByOwnerIdResponse) Reset() {
	*x = BoardServiceGetAllByOwnerIdResponse{}
	mi := &file_board_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceGetAllByOwnerIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceGetAllByOwnerIdResponse) ProtoMessage() {}

func (x *BoardServiceGetAllByOwnerIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceGetAllByOwnerIdResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceGetAllByOwnerIdResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *BoardServiceGetAllByOwnerIdResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

// Ответ на создание доски
type BoardServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateResponse) Reset() {
	*x = BoardServiceCreateResponse{}
	mi := &file_board_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateResponse) ProtoMessage() {}

func (x *BoardServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *BoardServiceCreateResponse) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

// Доска
type Board struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID доски
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Название доски
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Описание доски
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_board_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Board) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_board_v1_board_proto protoreflect.FileDescriptor

const file_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x14board/v1/board.proto\x12\bboard.v1\x1a\x17validate/validate.proto\"\x87\x01\n" +
	"\x19BoardServiceCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescription\x12\"\n" +
	"\bowner_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\aownerId\"H\n" +
	"\"BoardServiceGetAllByOwnerIdRequest\x12\"\n" +
	"\bowner_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\aownerId\"N\n" +
	"#BoardServiceGetAllByOwnerIdResponse\x12'\n" +
	"\x06boards\x18\x01 \x03(\v2\x0f.board.v1.BoardR\x06boards\"7\n" +
	"\x1aBoardServiceCreateResponse\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\x03R\aboardId\"h\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId2\xd3\x01\n" +
	"\fBoardService\x12S\n" +
	"\x06Create\x12#.board.v1.BoardServiceCreateRequest\x1a$.board.v1.BoardServiceCreateResponse\x12n\n" +
	"\x0fGetAllByOwnerId\x12,.board.v1.BoardServiceGetAllByOwnerIdRequest\x1a-.board.v1.BoardServiceGetAllByOwnerIdResponseBFZDgithub.com/poymanov/codemania-task-board/pkg/proto/board/v1;board_v1b\x06proto3"

var (
	file_board_v1_board_proto_rawDescOnce sync.Once
	file_board_v1_board_proto_rawDescData []byte
)

func file_board_v1_board_proto_rawDescGZIP() []byte {
	file_board_v1_board_proto_rawDescOnce.Do(func() {
		file_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)))
	})
	return file_board_v1_board_proto_rawDescData
}

var (
	file_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
	file_board_v1_board_proto_goTypes  = []any{
		(*BoardServiceCreateRequest)(nil),           // 0: board.v1.BoardServiceCreateRequest
		(*BoardServiceGetAllByOwnerIdRequest)(nil),  // 1: board.v1.BoardServiceGetAllByOwnerIdRequest
		(*BoardServiceGetAllByOwnerIdResponse)(nil), // 2: board.v1.BoardServiceGetAllByOwnerIdResponse
		(*BoardServiceCreateResponse)(nil),          // 3: board.v1.BoardServiceCreateResponse
		(*Board)(nil),                               // 4: board.v1.Board
	}
)

var file_board_v1_board_proto_depIdxs = []int32{
	4, // 0: board.v1.BoardServiceGetAllByOwnerIdResponse.boards:type_name -> board.v1.Board
	0, // 1: board.v1.BoardService.Create:input_type -> board.v1.BoardServiceCreateRequest
	1, // 2: board.v1.BoardService.GetAllByOwnerId:input_type -> board.v1.BoardServiceGetAllByOwnerIdRequest
	3, // 3: board.v1.BoardService.Create:output_type -> board.v1.BoardServiceCreateResponse
	2, // 4: board.v1.BoardService.GetAllByOwnerId:output_type -> board.v1.BoardServiceGetAllByOwnerIdResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_board_v1_board_proto_init() }
func file_board_v1_board_proto_init() {
	if File_board_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_board_v1_board_proto_goTypes,
		DependencyIndexes: file_board_v1_board_proto_depIdxs,
		MessageInfos:      file_board_v1_board_proto_msgTypes,
	}.Build()
	File_board_v1_board_proto = out.File
	file_board_v1_board_proto_goTypes = nil
	file_board_v1_board_proto_depIdxs = nil
}
