// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: board/v1/board.proto

package board_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание доски
type BoardServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название доски
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Описание доски
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateRequest) Reset() {
	*x = BoardServiceCreateRequest{}
	mi := &file_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateRequest) ProtoMessage() {}

func (x *BoardServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardServiceCreateRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Запрос на получение всех досок по ID владельца
type BoardServiceGetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *GetAllFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceGetAllRequest) Reset() {
	*x = BoardServiceGetAllRequest{}
	mi := &file_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceGetAllRequest) ProtoMessage() {}

func (x *BoardServiceGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceGetAllRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceGetAllRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardServiceGetAllRequest) GetFilter() *GetAllFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Запрос на удаление доски
type BoardServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID доски
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceDeleteRequest) Reset() {
	*x = BoardServiceDeleteRequest{}
	mi := &file_board_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceDeleteRequest) ProtoMessage() {}

func (x *BoardServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*BoardServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *BoardServiceDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Запрос на создание колонки
type ColumnServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название колонки
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID доски
	BoardId       int64 `protobuf:"varint,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnServiceCreateRequest) Reset() {
	*x = ColumnServiceCreateRequest{}
	mi := &file_board_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnServiceCreateRequest) ProtoMessage() {}

func (x *ColumnServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ColumnServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnServiceCreateRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

// Ответ со списком всех досок
type BoardServiceGetAllResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список досок
	Boards        []*Board `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceGetAllResponse) Reset() {
	*x = BoardServiceGetAllResponse{}
	mi := &file_board_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceGetAllResponse) ProtoMessage() {}

func (x *BoardServiceGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceGetAllResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceGetAllResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *BoardServiceGetAllResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

// Ответ на создание доски
type BoardServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceCreateResponse) Reset() {
	*x = BoardServiceCreateResponse{}
	mi := &file_board_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceCreateResponse) ProtoMessage() {}

func (x *BoardServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *BoardServiceCreateResponse) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

// Ответ на удаление доски
type BoardServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardServiceDeleteResponse) Reset() {
	*x = BoardServiceDeleteResponse{}
	mi := &file_board_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardServiceDeleteResponse) ProtoMessage() {}

func (x *BoardServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*BoardServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{6}
}

// Ответ на создание колонки
type ColumnServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      int64                  `protobuf:"varint,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnServiceCreateResponse) Reset() {
	*x = ColumnServiceCreateResponse{}
	mi := &file_board_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnServiceCreateResponse) ProtoMessage() {}

func (x *ColumnServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ColumnServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *ColumnServiceCreateResponse) GetColumnId() int64 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

// Доска
type Board struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID доски
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Название доски
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Описание доски
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// ID владельца доски
	OwnerId       int64 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_board_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{8}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Board) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Фильтр для запроса по всем доскам
type GetAllFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID владельца доски
	OwnerId       *int64 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFilter) Reset() {
	*x = GetAllFilter{}
	mi := &file_board_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFilter) ProtoMessage() {}

func (x *GetAllFilter) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFilter.ProtoReflect.Descriptor instead.
func (*GetAllFilter) Descriptor() ([]byte, []int) {
	return file_board_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllFilter) GetOwnerId() int64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

var File_board_v1_board_proto protoreflect.FileDescriptor

const file_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x14board/v1/board.proto\x12\bboard.v1\x1a\x17validate/validate.proto\"\x87\x01\n" +
	"\x19BoardServiceCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescription\x12\"\n" +
	"\bowner_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\aownerId\"K\n" +
	"\x19BoardServiceGetAllRequest\x12.\n" +
	"\x06filter\x18\x01 \x01(\v2\x16.board.v1.GetAllFilterR\x06filter\"4\n" +
	"\x19BoardServiceDeleteRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\"]\n" +
	"\x1aColumnServiceCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\"\n" +
	"\bboard_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\aboardId\"E\n" +
	"\x1aBoardServiceGetAllResponse\x12'\n" +
	"\x06boards\x18\x01 \x03(\v2\x0f.board.v1.BoardR\x06boards\"7\n" +
	"\x1aBoardServiceCreateResponse\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\x03R\aboardId\"\x1c\n" +
	"\x1aBoardServiceDeleteResponse\":\n" +
	"\x1bColumnServiceCreateResponse\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\x03R\bcolumnId\"h\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\"D\n" +
	"\fGetAllFilter\x12'\n" +
	"\bowner_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01H\x00R\aownerId\x88\x01\x01B\v\n" +
	"\t_owner_id2\x8d\x02\n" +
	"\fBoardService\x12S\n" +
	"\x06Create\x12#.board.v1.BoardServiceCreateRequest\x1a$.board.v1.BoardServiceCreateResponse\x12S\n" +
	"\x06GetAll\x12#.board.v1.BoardServiceGetAllRequest\x1a$.board.v1.BoardServiceGetAllResponse\x12S\n" +
	"\x06Delete\x12#.board.v1.BoardServiceDeleteRequest\x1a$.board.v1.BoardServiceDeleteResponse2f\n" +
	"\rColumnService\x12U\n" +
	"\x06Create\x12$.board.v1.ColumnServiceCreateRequest\x1a%.board.v1.ColumnServiceCreateResponseBFZDgithub.com/poymanov/codemania-task-board/pkg/proto/board/v1;board_v1b\x06proto3"

var (
	file_board_v1_board_proto_rawDescOnce sync.Once
	file_board_v1_board_proto_rawDescData []byte
)

func file_board_v1_board_proto_rawDescGZIP() []byte {
	file_board_v1_board_proto_rawDescOnce.Do(func() {
		file_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)))
	})
	return file_board_v1_board_proto_rawDescData
}

var (
	file_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
	file_board_v1_board_proto_goTypes  = []any{
		(*BoardServiceCreateRequest)(nil),   // 0: board.v1.BoardServiceCreateRequest
		(*BoardServiceGetAllRequest)(nil),   // 1: board.v1.BoardServiceGetAllRequest
		(*BoardServiceDeleteRequest)(nil),   // 2: board.v1.BoardServiceDeleteRequest
		(*ColumnServiceCreateRequest)(nil),  // 3: board.v1.ColumnServiceCreateRequest
		(*BoardServiceGetAllResponse)(nil),  // 4: board.v1.BoardServiceGetAllResponse
		(*BoardServiceCreateResponse)(nil),  // 5: board.v1.BoardServiceCreateResponse
		(*BoardServiceDeleteResponse)(nil),  // 6: board.v1.BoardServiceDeleteResponse
		(*ColumnServiceCreateResponse)(nil), // 7: board.v1.ColumnServiceCreateResponse
		(*Board)(nil),                       // 8: board.v1.Board
		(*GetAllFilter)(nil),                // 9: board.v1.GetAllFilter
	}
)

var file_board_v1_board_proto_depIdxs = []int32{
	9, // 0: board.v1.BoardServiceGetAllRequest.filter:type_name -> board.v1.GetAllFilter
	8, // 1: board.v1.BoardServiceGetAllResponse.boards:type_name -> board.v1.Board
	0, // 2: board.v1.BoardService.Create:input_type -> board.v1.BoardServiceCreateRequest
	1, // 3: board.v1.BoardService.GetAll:input_type -> board.v1.BoardServiceGetAllRequest
	2, // 4: board.v1.BoardService.Delete:input_type -> board.v1.BoardServiceDeleteRequest
	3, // 5: board.v1.ColumnService.Create:input_type -> board.v1.ColumnServiceCreateRequest
	5, // 6: board.v1.BoardService.Create:output_type -> board.v1.BoardServiceCreateResponse
	4, // 7: board.v1.BoardService.GetAll:output_type -> board.v1.BoardServiceGetAllResponse
	6, // 8: board.v1.BoardService.Delete:output_type -> board.v1.BoardServiceDeleteResponse
	7, // 9: board.v1.ColumnService.Create:output_type -> board.v1.ColumnServiceCreateResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_board_v1_board_proto_init() }
func file_board_v1_board_proto_init() {
	if File_board_v1_board_proto != nil {
		return
	}
	file_board_v1_board_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_v1_board_proto_rawDesc), len(file_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_board_v1_board_proto_goTypes,
		DependencyIndexes: file_board_v1_board_proto_depIdxs,
		MessageInfos:      file_board_v1_board_proto_msgTypes,
	}.Build()
	File_board_v1_board_proto = out.File
	file_board_v1_board_proto_goTypes = nil
	file_board_v1_board_proto_depIdxs = nil
}
