// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: board/v1/board.proto

package board_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BoardServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateRequestMultiError, or nil if none found.
func (m *BoardServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOwnerId() < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "OwnerId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceCreateRequestMultiError(errors)
	}

	return nil
}

// BoardServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceCreateRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateRequestMultiError) AllErrors() []error { return m }

// BoardServiceCreateRequestValidationError is the validation error returned by
// BoardServiceCreateRequest.Validate if the designated constraints aren't met.
type BoardServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateRequestValidationError) ErrorName() string {
	return "BoardServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceGetAllRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllRequestMultiError, or nil if none found.
func (m *BoardServiceGetAllRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BoardServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BoardServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BoardServiceGetAllRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BoardServiceGetAllRequestMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceGetAllRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceGetAllRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllRequestMultiError) AllErrors() []error { return m }

// BoardServiceGetAllRequestValidationError is the validation error returned by
// BoardServiceGetAllRequest.Validate if the designated constraints aren't met.
type BoardServiceGetAllRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllRequestValidationError) ErrorName() string {
	return "BoardServiceGetAllRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllRequestValidationError{}

// Validate checks the field values on BoardServiceDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceDeleteRequestMultiError, or nil if none found.
func (m *BoardServiceDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := BoardServiceDeleteRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceDeleteRequestMultiError(errors)
	}

	return nil
}

// BoardServiceDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceDeleteRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceDeleteRequestMultiError) AllErrors() []error { return m }

// BoardServiceDeleteRequestValidationError is the validation error returned by
// BoardServiceDeleteRequest.Validate if the designated constraints aren't met.
type BoardServiceDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceDeleteRequestValidationError) ErrorName() string {
	return "BoardServiceDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceDeleteRequestValidationError{}

// Validate checks the field values on ColumnServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceCreateRequestMultiError, or nil if none found.
func (m *ColumnServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ColumnServiceCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetBoardId() < 1 {
		err := ColumnServiceCreateRequestValidationError{
			field:  "BoardId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ColumnServiceCreateRequestMultiError(errors)
	}

	return nil
}

// ColumnServiceCreateRequestMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceCreateRequest.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceCreateRequestMultiError) AllErrors() []error { return m }

// ColumnServiceCreateRequestValidationError is the validation error returned
// by ColumnServiceCreateRequest.Validate if the designated constraints aren't met.
type ColumnServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceCreateRequestValidationError) ErrorName() string {
	return "ColumnServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceCreateRequestValidationError{}

// Validate checks the field values on ColumnServiceGetAllRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceGetAllRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceGetAllRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceGetAllRequestMultiError, or nil if none found.
func (m *ColumnServiceGetAllRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceGetAllRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ColumnServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ColumnServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ColumnServiceGetAllRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSort()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ColumnServiceGetAllRequestValidationError{
					field:  "Sort",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ColumnServiceGetAllRequestValidationError{
					field:  "Sort",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSort()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ColumnServiceGetAllRequestValidationError{
				field:  "Sort",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ColumnServiceGetAllRequestMultiError(errors)
	}

	return nil
}

// ColumnServiceGetAllRequestMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceGetAllRequest.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceGetAllRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceGetAllRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceGetAllRequestMultiError) AllErrors() []error { return m }

// ColumnServiceGetAllRequestValidationError is the validation error returned
// by ColumnServiceGetAllRequest.Validate if the designated constraints aren't met.
type ColumnServiceGetAllRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceGetAllRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceGetAllRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceGetAllRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceGetAllRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceGetAllRequestValidationError) ErrorName() string {
	return "ColumnServiceGetAllRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceGetAllRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceGetAllRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceGetAllRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceGetAllRequestValidationError{}

// Validate checks the field values on ColumnServiceDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceDeleteRequestMultiError, or nil if none found.
func (m *ColumnServiceDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := ColumnServiceDeleteRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ColumnServiceDeleteRequestMultiError(errors)
	}

	return nil
}

// ColumnServiceDeleteRequestMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceDeleteRequest.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceDeleteRequestMultiError) AllErrors() []error { return m }

// ColumnServiceDeleteRequestValidationError is the validation error returned
// by ColumnServiceDeleteRequest.Validate if the designated constraints aren't met.
type ColumnServiceDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceDeleteRequestValidationError) ErrorName() string {
	return "ColumnServiceDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceDeleteRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceGetAllResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllResponseMultiError, or nil if none found.
func (m *BoardServiceGetAllResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBoards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BoardServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BoardServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BoardServiceGetAllResponseValidationError{
					field:  fmt.Sprintf("Boards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BoardServiceGetAllResponseMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceGetAllResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceGetAllResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllResponseMultiError) AllErrors() []error { return m }

// BoardServiceGetAllResponseValidationError is the validation error returned
// by BoardServiceGetAllResponse.Validate if the designated constraints aren't met.
type BoardServiceGetAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllResponseValidationError) ErrorName() string {
	return "BoardServiceGetAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllResponseValidationError{}

// Validate checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateResponseMultiError, or nil if none found.
func (m *BoardServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BoardId

	if len(errors) > 0 {
		return BoardServiceCreateResponseMultiError(errors)
	}

	return nil
}

// BoardServiceCreateResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceCreateResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateResponseMultiError) AllErrors() []error { return m }

// BoardServiceCreateResponseValidationError is the validation error returned
// by BoardServiceCreateResponse.Validate if the designated constraints aren't met.
type BoardServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateResponseValidationError) ErrorName() string {
	return "BoardServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateResponseValidationError{}

// Validate checks the field values on BoardServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceDeleteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceDeleteResponseMultiError, or nil if none found.
func (m *BoardServiceDeleteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceDeleteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BoardServiceDeleteResponseMultiError(errors)
	}

	return nil
}

// BoardServiceDeleteResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceDeleteResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceDeleteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceDeleteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceDeleteResponseMultiError) AllErrors() []error { return m }

// BoardServiceDeleteResponseValidationError is the validation error returned
// by BoardServiceDeleteResponse.Validate if the designated constraints aren't met.
type BoardServiceDeleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceDeleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceDeleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceDeleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceDeleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceDeleteResponseValidationError) ErrorName() string {
	return "BoardServiceDeleteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceDeleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceDeleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceDeleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceDeleteResponseValidationError{}

// Validate checks the field values on ColumnServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceCreateResponseMultiError, or nil if none found.
func (m *ColumnServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ColumnId

	if len(errors) > 0 {
		return ColumnServiceCreateResponseMultiError(errors)
	}

	return nil
}

// ColumnServiceCreateResponseMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceCreateResponse.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceCreateResponseMultiError) AllErrors() []error { return m }

// ColumnServiceCreateResponseValidationError is the validation error returned
// by ColumnServiceCreateResponse.Validate if the designated constraints
// aren't met.
type ColumnServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceCreateResponseValidationError) ErrorName() string {
	return "ColumnServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceCreateResponseValidationError{}

// Validate checks the field values on ColumnServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceGetAllResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceGetAllResponseMultiError, or nil if none found.
func (m *ColumnServiceGetAllResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceGetAllResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetColumns() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ColumnServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Columns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ColumnServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Columns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ColumnServiceGetAllResponseValidationError{
					field:  fmt.Sprintf("Columns[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ColumnServiceGetAllResponseMultiError(errors)
	}

	return nil
}

// ColumnServiceGetAllResponseMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceGetAllResponse.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceGetAllResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceGetAllResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceGetAllResponseMultiError) AllErrors() []error { return m }

// ColumnServiceGetAllResponseValidationError is the validation error returned
// by ColumnServiceGetAllResponse.Validate if the designated constraints
// aren't met.
type ColumnServiceGetAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceGetAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceGetAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceGetAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceGetAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceGetAllResponseValidationError) ErrorName() string {
	return "ColumnServiceGetAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceGetAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceGetAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceGetAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceGetAllResponseValidationError{}

// Validate checks the field values on ColumnServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceDeleteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceDeleteResponseMultiError, or nil if none found.
func (m *ColumnServiceDeleteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceDeleteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ColumnServiceDeleteResponseMultiError(errors)
	}

	return nil
}

// ColumnServiceDeleteResponseMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceDeleteResponse.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceDeleteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceDeleteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceDeleteResponseMultiError) AllErrors() []error { return m }

// ColumnServiceDeleteResponseValidationError is the validation error returned
// by ColumnServiceDeleteResponse.Validate if the designated constraints
// aren't met.
type ColumnServiceDeleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceDeleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceDeleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceDeleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceDeleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceDeleteResponseValidationError) ErrorName() string {
	return "ColumnServiceDeleteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceDeleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceDeleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceDeleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceDeleteResponseValidationError{}

// Validate checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Board) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BoardMultiError, or nil if none found.
func (m *Board) ValidateAll() error {
	return m.validate(true)
}

func (m *Board) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for OwnerId

	if len(errors) > 0 {
		return BoardMultiError(errors)
	}

	return nil
}

// BoardMultiError is an error wrapping multiple validation errors returned by
// Board.ValidateAll() if the designated constraints aren't met.
type BoardMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardMultiError) AllErrors() []error { return m }

// BoardValidationError is the validation error returned by Board.Validate if
// the designated constraints aren't met.
type BoardValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardValidationError) ErrorName() string { return "BoardValidationError" }

// Error satisfies the builtin error interface
func (e BoardValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoard.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardValidationError{}

// Validate checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Column) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ColumnMultiError, or nil if none found.
func (m *Column) ValidateAll() error {
	return m.validate(true)
}

func (m *Column) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Position

	// no validation rules for BoardId

	if len(errors) > 0 {
		return ColumnMultiError(errors)
	}

	return nil
}

// ColumnMultiError is an error wrapping multiple validation errors returned by
// Column.ValidateAll() if the designated constraints aren't met.
type ColumnMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnMultiError) AllErrors() []error { return m }

// ColumnValidationError is the validation error returned by Column.Validate if
// the designated constraints aren't met.
type ColumnValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnValidationError) ErrorName() string { return "ColumnValidationError" }

// Error satisfies the builtin error interface
func (e ColumnValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumn.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnValidationError{}

// Validate checks the field values on BoardGetAllFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BoardGetAllFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardGetAllFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardGetAllFilterMultiError, or nil if none found.
func (m *BoardGetAllFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardGetAllFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.OwnerId != nil {
		if m.GetOwnerId() < 1 {
			err := BoardGetAllFilterValidationError{
				field:  "OwnerId",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return BoardGetAllFilterMultiError(errors)
	}

	return nil
}

// BoardGetAllFilterMultiError is an error wrapping multiple validation errors
// returned by BoardGetAllFilter.ValidateAll() if the designated constraints
// aren't met.
type BoardGetAllFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardGetAllFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardGetAllFilterMultiError) AllErrors() []error { return m }

// BoardGetAllFilterValidationError is the validation error returned by
// BoardGetAllFilter.Validate if the designated constraints aren't met.
type BoardGetAllFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardGetAllFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardGetAllFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardGetAllFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardGetAllFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardGetAllFilterValidationError) ErrorName() string {
	return "BoardGetAllFilterValidationError"
}

// Error satisfies the builtin error interface
func (e BoardGetAllFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardGetAllFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardGetAllFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardGetAllFilterValidationError{}

// Validate checks the field values on ColumnGetAllFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnGetAllFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnGetAllFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnGetAllFilterMultiError, or nil if none found.
func (m *ColumnGetAllFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnGetAllFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.BoardId != nil {
		if m.GetBoardId() < 1 {
			err := ColumnGetAllFilterValidationError{
				field:  "BoardId",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return ColumnGetAllFilterMultiError(errors)
	}

	return nil
}

// ColumnGetAllFilterMultiError is an error wrapping multiple validation errors
// returned by ColumnGetAllFilter.ValidateAll() if the designated constraints
// aren't met.
type ColumnGetAllFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnGetAllFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnGetAllFilterMultiError) AllErrors() []error { return m }

// ColumnGetAllFilterValidationError is the validation error returned by
// ColumnGetAllFilter.Validate if the designated constraints aren't met.
type ColumnGetAllFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnGetAllFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnGetAllFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnGetAllFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnGetAllFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnGetAllFilterValidationError) ErrorName() string {
	return "ColumnGetAllFilterValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnGetAllFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnGetAllFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnGetAllFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnGetAllFilterValidationError{}

// Validate checks the field values on ColumnGetAllSort with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ColumnGetAllSort) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnGetAllSort with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnGetAllSortMultiError, or nil if none found.
func (m *ColumnGetAllSort) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnGetAllSort) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Position != nil {
		if utf8.RuneCountInString(m.GetPosition()) < 1 {
			err := ColumnGetAllSortValidationError{
				field:  "Position",
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return ColumnGetAllSortMultiError(errors)
	}

	return nil
}

// ColumnGetAllSortMultiError is an error wrapping multiple validation errors
// returned by ColumnGetAllSort.ValidateAll() if the designated constraints
// aren't met.
type ColumnGetAllSortMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnGetAllSortMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnGetAllSortMultiError) AllErrors() []error { return m }

// ColumnGetAllSortValidationError is the validation error returned by
// ColumnGetAllSort.Validate if the designated constraints aren't met.
type ColumnGetAllSortValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnGetAllSortValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnGetAllSortValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnGetAllSortValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnGetAllSortValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnGetAllSortValidationError) ErrorName() string { return "ColumnGetAllSortValidationError" }

// Error satisfies the builtin error interface
func (e ColumnGetAllSortValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnGetAllSort.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnGetAllSortValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnGetAllSortValidationError{}
