// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: board/v1/board.proto

package board_v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoardService_Create_FullMethodName = "/board.v1.BoardService/Create"
	BoardService_GetAll_FullMethodName = "/board.v1.BoardService/GetAll"
	BoardService_Delete_FullMethodName = "/board.v1.BoardService/Delete"
)

// BoardServiceClient is the client API for BoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoardServiceClient interface {
	Create(ctx context.Context, in *BoardServiceCreateRequest, opts ...grpc.CallOption) (*BoardServiceCreateResponse, error)
	GetAll(ctx context.Context, in *BoardServiceGetAllRequest, opts ...grpc.CallOption) (*BoardServiceGetAllResponse, error)
	Delete(ctx context.Context, in *BoardServiceDeleteRequest, opts ...grpc.CallOption) (*BoardServiceDeleteResponse, error)
}

type boardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoardServiceClient(cc grpc.ClientConnInterface) BoardServiceClient {
	return &boardServiceClient{cc}
}

func (c *boardServiceClient) Create(ctx context.Context, in *BoardServiceCreateRequest, opts ...grpc.CallOption) (*BoardServiceCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardServiceCreateResponse)
	err := c.cc.Invoke(ctx, BoardService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) GetAll(ctx context.Context, in *BoardServiceGetAllRequest, opts ...grpc.CallOption) (*BoardServiceGetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardServiceGetAllResponse)
	err := c.cc.Invoke(ctx, BoardService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) Delete(ctx context.Context, in *BoardServiceDeleteRequest, opts ...grpc.CallOption) (*BoardServiceDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardServiceDeleteResponse)
	err := c.cc.Invoke(ctx, BoardService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardServiceServer is the server API for BoardService service.
// All implementations must embed UnimplementedBoardServiceServer
// for forward compatibility.
type BoardServiceServer interface {
	Create(context.Context, *BoardServiceCreateRequest) (*BoardServiceCreateResponse, error)
	GetAll(context.Context, *BoardServiceGetAllRequest) (*BoardServiceGetAllResponse, error)
	Delete(context.Context, *BoardServiceDeleteRequest) (*BoardServiceDeleteResponse, error)
	mustEmbedUnimplementedBoardServiceServer()
}

// UnimplementedBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoardServiceServer struct{}

func (UnimplementedBoardServiceServer) Create(context.Context, *BoardServiceCreateRequest) (*BoardServiceCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}

func (UnimplementedBoardServiceServer) GetAll(context.Context, *BoardServiceGetAllRequest) (*BoardServiceGetAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}

func (UnimplementedBoardServiceServer) Delete(context.Context, *BoardServiceDeleteRequest) (*BoardServiceDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBoardServiceServer) mustEmbedUnimplementedBoardServiceServer() {}
func (UnimplementedBoardServiceServer) testEmbeddedByValue()                      {}

// UnsafeBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoardServiceServer will
// result in compilation errors.
type UnsafeBoardServiceServer interface {
	mustEmbedUnimplementedBoardServiceServer()
}

func RegisterBoardServiceServer(s grpc.ServiceRegistrar, srv BoardServiceServer) {
	// If the following call panics, it indicates UnimplementedBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoardService_ServiceDesc, srv)
}

func _BoardService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Create(ctx, req.(*BoardServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardServiceGetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).GetAll(ctx, req.(*BoardServiceGetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardServiceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Delete(ctx, req.(*BoardServiceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoardService_ServiceDesc is the grpc.ServiceDesc for BoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "board.v1.BoardService",
	HandlerType: (*BoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BoardService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BoardService_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BoardService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "board/v1/board.proto",
}

const (
	ColumnService_Create_FullMethodName = "/board.v1.ColumnService/Create"
)

// ColumnServiceClient is the client API for ColumnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColumnServiceClient interface {
	Create(ctx context.Context, in *ColumnServiceCreateRequest, opts ...grpc.CallOption) (*ColumnServiceCreateResponse, error)
}

type columnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColumnServiceClient(cc grpc.ClientConnInterface) ColumnServiceClient {
	return &columnServiceClient{cc}
}

func (c *columnServiceClient) Create(ctx context.Context, in *ColumnServiceCreateRequest, opts ...grpc.CallOption) (*ColumnServiceCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ColumnServiceCreateResponse)
	err := c.cc.Invoke(ctx, ColumnService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColumnServiceServer is the server API for ColumnService service.
// All implementations must embed UnimplementedColumnServiceServer
// for forward compatibility.
type ColumnServiceServer interface {
	Create(context.Context, *ColumnServiceCreateRequest) (*ColumnServiceCreateResponse, error)
	mustEmbedUnimplementedColumnServiceServer()
}

// UnimplementedColumnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedColumnServiceServer struct{}

func (UnimplementedColumnServiceServer) Create(context.Context, *ColumnServiceCreateRequest) (*ColumnServiceCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedColumnServiceServer) mustEmbedUnimplementedColumnServiceServer() {}
func (UnimplementedColumnServiceServer) testEmbeddedByValue()                       {}

// UnsafeColumnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColumnServiceServer will
// result in compilation errors.
type UnsafeColumnServiceServer interface {
	mustEmbedUnimplementedColumnServiceServer()
}

func RegisterColumnServiceServer(s grpc.ServiceRegistrar, srv ColumnServiceServer) {
	// If the following call panics, it indicates UnimplementedColumnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ColumnService_ServiceDesc, srv)
}

func _ColumnService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColumnService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnServiceServer).Create(ctx, req.(*ColumnServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ColumnService_ServiceDesc is the grpc.ServiceDesc for ColumnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColumnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "board.v1.ColumnService",
	HandlerType: (*ColumnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ColumnService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "board/v1/board.proto",
}
