// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: board/v1/board.proto

package board_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BoardServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateRequestMultiError, or nil if none found.
func (m *BoardServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOwnerId() < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "OwnerId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceCreateRequestMultiError(errors)
	}

	return nil
}

// BoardServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceCreateRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateRequestMultiError) AllErrors() []error { return m }

// BoardServiceCreateRequestValidationError is the validation error returned by
// BoardServiceCreateRequest.Validate if the designated constraints aren't met.
type BoardServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateRequestValidationError) ErrorName() string {
	return "BoardServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllByOwnerIdRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *BoardServiceGetAllByOwnerIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllByOwnerIdRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllByOwnerIdRequestMultiError, or nil if none found.
func (m *BoardServiceGetAllByOwnerIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllByOwnerIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() < 1 {
		err := BoardServiceGetAllByOwnerIdRequestValidationError{
			field:  "OwnerId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceGetAllByOwnerIdRequestMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllByOwnerIdRequestMultiError is an error wrapping multiple
// validation errors returned by
// BoardServiceGetAllByOwnerIdRequest.ValidateAll() if the designated
// constraints aren't met.
type BoardServiceGetAllByOwnerIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllByOwnerIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllByOwnerIdRequestMultiError) AllErrors() []error { return m }

// BoardServiceGetAllByOwnerIdRequestValidationError is the validation error
// returned by BoardServiceGetAllByOwnerIdRequest.Validate if the designated
// constraints aren't met.
type BoardServiceGetAllByOwnerIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllByOwnerIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllByOwnerIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllByOwnerIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllByOwnerIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllByOwnerIdRequestValidationError) ErrorName() string {
	return "BoardServiceGetAllByOwnerIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllByOwnerIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllByOwnerIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllByOwnerIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllByOwnerIdRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllByOwnerIdResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *BoardServiceGetAllByOwnerIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllByOwnerIdResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllByOwnerIdResponseMultiError, or nil if none found.
func (m *BoardServiceGetAllByOwnerIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllByOwnerIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBoards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BoardServiceGetAllByOwnerIdResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BoardServiceGetAllByOwnerIdResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BoardServiceGetAllByOwnerIdResponseValidationError{
					field:  fmt.Sprintf("Boards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BoardServiceGetAllByOwnerIdResponseMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllByOwnerIdResponseMultiError is an error wrapping multiple
// validation errors returned by
// BoardServiceGetAllByOwnerIdResponse.ValidateAll() if the designated
// constraints aren't met.
type BoardServiceGetAllByOwnerIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllByOwnerIdResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllByOwnerIdResponseMultiError) AllErrors() []error { return m }

// BoardServiceGetAllByOwnerIdResponseValidationError is the validation error
// returned by BoardServiceGetAllByOwnerIdResponse.Validate if the designated
// constraints aren't met.
type BoardServiceGetAllByOwnerIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllByOwnerIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllByOwnerIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllByOwnerIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllByOwnerIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllByOwnerIdResponseValidationError) ErrorName() string {
	return "BoardServiceGetAllByOwnerIdResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllByOwnerIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllByOwnerIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllByOwnerIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllByOwnerIdResponseValidationError{}

// Validate checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateResponseMultiError, or nil if none found.
func (m *BoardServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BoardId

	if len(errors) > 0 {
		return BoardServiceCreateResponseMultiError(errors)
	}

	return nil
}

// BoardServiceCreateResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceCreateResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateResponseMultiError) AllErrors() []error { return m }

// BoardServiceCreateResponseValidationError is the validation error returned
// by BoardServiceCreateResponse.Validate if the designated constraints aren't met.
type BoardServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateResponseValidationError) ErrorName() string {
	return "BoardServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateResponseValidationError{}

// Validate checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Board) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BoardMultiError, or nil if none found.
func (m *Board) ValidateAll() error {
	return m.validate(true)
}

func (m *Board) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for OwnerId

	if len(errors) > 0 {
		return BoardMultiError(errors)
	}

	return nil
}

// BoardMultiError is an error wrapping multiple validation errors returned by
// Board.ValidateAll() if the designated constraints aren't met.
type BoardMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardMultiError) AllErrors() []error { return m }

// BoardValidationError is the validation error returned by Board.Validate if
// the designated constraints aren't met.
type BoardValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardValidationError) ErrorName() string { return "BoardValidationError" }

// Error satisfies the builtin error interface
func (e BoardValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoard.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardValidationError{}
