// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: board/v1/board.proto

package board_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BoardServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateRequestMultiError, or nil if none found.
func (m *BoardServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOwnerId() < 1 {
		err := BoardServiceCreateRequestValidationError{
			field:  "OwnerId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceCreateRequestMultiError(errors)
	}

	return nil
}

// BoardServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceCreateRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateRequestMultiError) AllErrors() []error { return m }

// BoardServiceCreateRequestValidationError is the validation error returned by
// BoardServiceCreateRequest.Validate if the designated constraints aren't met.
type BoardServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateRequestValidationError) ErrorName() string {
	return "BoardServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceGetAllRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllRequestMultiError, or nil if none found.
func (m *BoardServiceGetAllRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BoardServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BoardServiceGetAllRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BoardServiceGetAllRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BoardServiceGetAllRequestMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceGetAllRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceGetAllRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllRequestMultiError) AllErrors() []error { return m }

// BoardServiceGetAllRequestValidationError is the validation error returned by
// BoardServiceGetAllRequest.Validate if the designated constraints aren't met.
type BoardServiceGetAllRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllRequestValidationError) ErrorName() string {
	return "BoardServiceGetAllRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllRequestValidationError{}

// Validate checks the field values on BoardServiceDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceDeleteRequestMultiError, or nil if none found.
func (m *BoardServiceDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := BoardServiceDeleteRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardServiceDeleteRequestMultiError(errors)
	}

	return nil
}

// BoardServiceDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by BoardServiceDeleteRequest.ValidateAll() if the
// designated constraints aren't met.
type BoardServiceDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceDeleteRequestMultiError) AllErrors() []error { return m }

// BoardServiceDeleteRequestValidationError is the validation error returned by
// BoardServiceDeleteRequest.Validate if the designated constraints aren't met.
type BoardServiceDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceDeleteRequestValidationError) ErrorName() string {
	return "BoardServiceDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceDeleteRequestValidationError{}

// Validate checks the field values on ColumnServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceCreateRequestMultiError, or nil if none found.
func (m *ColumnServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ColumnServiceCreateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetBoardId() < 1 {
		err := ColumnServiceCreateRequestValidationError{
			field:  "BoardId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ColumnServiceCreateRequestMultiError(errors)
	}

	return nil
}

// ColumnServiceCreateRequestMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceCreateRequest.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceCreateRequestMultiError) AllErrors() []error { return m }

// ColumnServiceCreateRequestValidationError is the validation error returned
// by ColumnServiceCreateRequest.Validate if the designated constraints aren't met.
type ColumnServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceCreateRequestValidationError) ErrorName() string {
	return "ColumnServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceCreateRequestValidationError{}

// Validate checks the field values on BoardServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceGetAllResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceGetAllResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceGetAllResponseMultiError, or nil if none found.
func (m *BoardServiceGetAllResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceGetAllResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBoards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BoardServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BoardServiceGetAllResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BoardServiceGetAllResponseValidationError{
					field:  fmt.Sprintf("Boards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BoardServiceGetAllResponseMultiError(errors)
	}

	return nil
}

// BoardServiceGetAllResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceGetAllResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceGetAllResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceGetAllResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceGetAllResponseMultiError) AllErrors() []error { return m }

// BoardServiceGetAllResponseValidationError is the validation error returned
// by BoardServiceGetAllResponse.Validate if the designated constraints aren't met.
type BoardServiceGetAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceGetAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceGetAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceGetAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceGetAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceGetAllResponseValidationError) ErrorName() string {
	return "BoardServiceGetAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceGetAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceGetAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceGetAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceGetAllResponseValidationError{}

// Validate checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceCreateResponseMultiError, or nil if none found.
func (m *BoardServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BoardId

	if len(errors) > 0 {
		return BoardServiceCreateResponseMultiError(errors)
	}

	return nil
}

// BoardServiceCreateResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceCreateResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceCreateResponseMultiError) AllErrors() []error { return m }

// BoardServiceCreateResponseValidationError is the validation error returned
// by BoardServiceCreateResponse.Validate if the designated constraints aren't met.
type BoardServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceCreateResponseValidationError) ErrorName() string {
	return "BoardServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceCreateResponseValidationError{}

// Validate checks the field values on BoardServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BoardServiceDeleteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardServiceDeleteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardServiceDeleteResponseMultiError, or nil if none found.
func (m *BoardServiceDeleteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardServiceDeleteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BoardServiceDeleteResponseMultiError(errors)
	}

	return nil
}

// BoardServiceDeleteResponseMultiError is an error wrapping multiple
// validation errors returned by BoardServiceDeleteResponse.ValidateAll() if
// the designated constraints aren't met.
type BoardServiceDeleteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardServiceDeleteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardServiceDeleteResponseMultiError) AllErrors() []error { return m }

// BoardServiceDeleteResponseValidationError is the validation error returned
// by BoardServiceDeleteResponse.Validate if the designated constraints aren't met.
type BoardServiceDeleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardServiceDeleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardServiceDeleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardServiceDeleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardServiceDeleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardServiceDeleteResponseValidationError) ErrorName() string {
	return "BoardServiceDeleteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BoardServiceDeleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardServiceDeleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardServiceDeleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardServiceDeleteResponseValidationError{}

// Validate checks the field values on ColumnServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ColumnServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ColumnServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ColumnServiceCreateResponseMultiError, or nil if none found.
func (m *ColumnServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ColumnServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ColumnId

	if len(errors) > 0 {
		return ColumnServiceCreateResponseMultiError(errors)
	}

	return nil
}

// ColumnServiceCreateResponseMultiError is an error wrapping multiple
// validation errors returned by ColumnServiceCreateResponse.ValidateAll() if
// the designated constraints aren't met.
type ColumnServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnServiceCreateResponseMultiError) AllErrors() []error { return m }

// ColumnServiceCreateResponseValidationError is the validation error returned
// by ColumnServiceCreateResponse.Validate if the designated constraints
// aren't met.
type ColumnServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnServiceCreateResponseValidationError) ErrorName() string {
	return "ColumnServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ColumnServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumnServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnServiceCreateResponseValidationError{}

// Validate checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Board) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Board with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BoardMultiError, or nil if none found.
func (m *Board) ValidateAll() error {
	return m.validate(true)
}

func (m *Board) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for OwnerId

	if len(errors) > 0 {
		return BoardMultiError(errors)
	}

	return nil
}

// BoardMultiError is an error wrapping multiple validation errors returned by
// Board.ValidateAll() if the designated constraints aren't met.
type BoardMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardMultiError) AllErrors() []error { return m }

// BoardValidationError is the validation error returned by Board.Validate if
// the designated constraints aren't met.
type BoardValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardValidationError) ErrorName() string { return "BoardValidationError" }

// Error satisfies the builtin error interface
func (e BoardValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoard.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardValidationError{}

// Validate checks the field values on GetAllFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAllFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAllFilterMultiError, or
// nil if none found.
func (m *GetAllFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.OwnerId != nil {
		if m.GetOwnerId() < 1 {
			err := GetAllFilterValidationError{
				field:  "OwnerId",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return GetAllFilterMultiError(errors)
	}

	return nil
}

// GetAllFilterMultiError is an error wrapping multiple validation errors
// returned by GetAllFilter.ValidateAll() if the designated constraints aren't met.
type GetAllFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllFilterMultiError) AllErrors() []error { return m }

// GetAllFilterValidationError is the validation error returned by
// GetAllFilter.Validate if the designated constraints aren't met.
type GetAllFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllFilterValidationError) ErrorName() string { return "GetAllFilterValidationError" }

// Error satisfies the builtin error interface
func (e GetAllFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllFilterValidationError{}
