// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/poymanov/codemania-task-board/board/internal/domain/column"
	mock "github.com/stretchr/testify/mock"
)

// NewColumnRepository creates a new instance of ColumnRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewColumnRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ColumnRepository {
	mock := &ColumnRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ColumnRepository is an autogenerated mock type for the ColumnRepository type
type ColumnRepository struct {
	mock.Mock
}

type ColumnRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ColumnRepository) EXPECT() *ColumnRepository_Expecter {
	return &ColumnRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ColumnRepository
func (_mock *ColumnRepository) Create(ctx context.Context, newColumn column.NewColumn) (int, error) {
	ret := _mock.Called(ctx, newColumn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, column.NewColumn) (int, error)); ok {
		return returnFunc(ctx, newColumn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, column.NewColumn) int); ok {
		r0 = returnFunc(ctx, newColumn)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, column.NewColumn) error); ok {
		r1 = returnFunc(ctx, newColumn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ColumnRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ColumnRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newColumn column.NewColumn
func (_e *ColumnRepository_Expecter) Create(ctx interface{}, newColumn interface{}) *ColumnRepository_Create_Call {
	return &ColumnRepository_Create_Call{Call: _e.mock.On("Create", ctx, newColumn)}
}

func (_c *ColumnRepository_Create_Call) Run(run func(ctx context.Context, newColumn column.NewColumn)) *ColumnRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 column.NewColumn
		if args[1] != nil {
			arg1 = args[1].(column.NewColumn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ColumnRepository_Create_Call) Return(n int, err error) *ColumnRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ColumnRepository_Create_Call) RunAndReturn(run func(ctx context.Context, newColumn column.NewColumn) (int, error)) *ColumnRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ColumnRepository
func (_mock *ColumnRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ColumnRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ColumnRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ColumnRepository_Expecter) Delete(ctx interface{}, id interface{}) *ColumnRepository_Delete_Call {
	return &ColumnRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ColumnRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *ColumnRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ColumnRepository_Delete_Call) Return(err error) *ColumnRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ColumnRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *ColumnRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type ColumnRepository
func (_mock *ColumnRepository) GetAll(ctx context.Context, filter column.GetAllFilter, sort column.GetAllSort) ([]column.Column, error) {
	ret := _mock.Called(ctx, filter, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []column.Column
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, column.GetAllFilter, column.GetAllSort) ([]column.Column, error)); ok {
		return returnFunc(ctx, filter, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, column.GetAllFilter, column.GetAllSort) []column.Column); ok {
		r0 = returnFunc(ctx, filter, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]column.Column)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, column.GetAllFilter, column.GetAllSort) error); ok {
		r1 = returnFunc(ctx, filter, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ColumnRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ColumnRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter column.GetAllFilter
//   - sort column.GetAllSort
func (_e *ColumnRepository_Expecter) GetAll(ctx interface{}, filter interface{}, sort interface{}) *ColumnRepository_GetAll_Call {
	return &ColumnRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filter, sort)}
}

func (_c *ColumnRepository_GetAll_Call) Run(run func(ctx context.Context, filter column.GetAllFilter, sort column.GetAllSort)) *ColumnRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 column.GetAllFilter
		if args[1] != nil {
			arg1 = args[1].(column.GetAllFilter)
		}
		var arg2 column.GetAllSort
		if args[2] != nil {
			arg2 = args[2].(column.GetAllSort)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ColumnRepository_GetAll_Call) Return(columns []column.Column, err error) *ColumnRepository_GetAll_Call {
	_c.Call.Return(columns, err)
	return _c
}

func (_c *ColumnRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, filter column.GetAllFilter, sort column.GetAllSort) ([]column.Column, error)) *ColumnRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
